import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:phosphor_flutter/phosphor_flutter.dart';

import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/dream_colors.dart';
import '../../../../core/utils/format_utils.dart';
import '../../services/ai_proxy_service.dart';
import '../../providers/copy_trading_provider.dart';

/// Broadcaster earnings dashboard, reached from Settings → Broadcasting.
///
/// Shows the broadcaster's real USDC earnings (a revenue share of the Phoenix
/// Flight builder fees generated by their copiers' volume), an earnings event
/// history, their own Phoenix trading PnL, and a payout request action.
class BroadcasterDashboardPage extends ConsumerStatefulWidget {
  const BroadcasterDashboardPage({super.key});

  @override
  ConsumerState<BroadcasterDashboardPage> createState() =>
      _BroadcasterDashboardPageState();
}

class _BroadcasterDashboardPageState
    extends ConsumerState<BroadcasterDashboardPage> {
  BroadcasterEarnings? _earnings;
  bool _loadingEarnings = false;
  bool _requestingPayout = false;

  @override
  void initState() {
    super.initState();
    Future.microtask(_refresh);
  }

  Future<void> _refresh() async {
    setState(() => _loadingEarnings = true);
    await ref.read(copyTradingProvider.notifier).refreshMyBroadcaster();
    final earnings = await ref
        .read(copyTradingProvider.notifier)
        .fetchBroadcasterEarnings();
    if (!mounted) return;
    setState(() {
      _earnings = earnings;
      _loadingEarnings = false;
    });
  }

  Future<void> _handlePayout() async {
    if (_requestingPayout) return;
    setState(() => _requestingPayout = true);
    try {
      final amount = await ref
          .read(copyTradingProvider.notifier)
          .requestPayout();
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Payout requested: ${formatUsdc(amount)}'),
          backgroundColor: context.dreamColors.surfaceVariant,
        ),
      );
      await _refresh();
    } on PayoutException catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(e.toString()),
          backgroundColor: context.dreamColors.surfaceVariant,
        ),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Payout failed: $e'),
          backgroundColor: context.dreamColors.surfaceVariant,
        ),
      );
    } finally {
      if (mounted) setState(() => _requestingPayout = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final colors = context.dreamColors;
    final state = ref.watch(copyTradingProvider);
    final me = state.myBroadcaster;
    final isRegistered = me != null;

    return Scaffold(
      backgroundColor: colors.background,
      appBar: AppBar(
        backgroundColor: colors.background,
        elevation: 0,
        scrolledUnderElevation: 0,
        leading: IconButton(
          icon: Icon(
            PhosphorIcons.caretLeft(PhosphorIconsStyle.bold),
            color: colors.onSurface,
            size: 20.r,
          ),
          onPressed: () => Navigator.of(context).maybePop(),
        ),
        title: Text(
          'Broadcasting',
          style: TextStyle(
            color: colors.onSurface,
            fontSize: 17.sp,
            fontWeight: FontWeight.w800,
          ),
        ),
      ),
      body: RefreshIndicator(
        color: AppColors.primary,
        backgroundColor: colors.surfaceVariant,
        onRefresh: _refresh,
        child: ListView(
          padding: EdgeInsets.fromLTRB(
            20.w,
            8.h,
            20.w,
            MediaQuery.paddingOf(context).bottom + 32.h,
          ),
          children: [
            if (!isRegistered)
              _RegisterCard(
                isRegistering: state.isRegisteringBroadcaster,
                onRegister: _showRegisterSheet,
              )
            else ...[
              _EarningsHero(
                earnings: _earnings,
                loading: _loadingEarnings,
                onPayout: _handlePayout,
                requestingPayout: _requestingPayout,
              ),
              SizedBox(height: 16.h),
              _StatsGrid(earnings: _earnings),
              SizedBox(height: 22.h),
              _SectionLabel(title: 'Earnings history'),
              SizedBox(height: 12.h),
              _HistoryList(earnings: _earnings, loading: _loadingEarnings),
              SizedBox(height: 22.h),
              _EditButton(onTap: _showRegisterSheet),
            ],
          ],
        ),
      ),
    );
  }

  Future<void> _showRegisterSheet() async {
    final me = ref.read(copyTradingProvider).myBroadcaster;
    final nameCtrl = TextEditingController(text: me?.label ?? '');
    final strategyCtrl = TextEditingController(text: me?.strategy ?? '');
    final twitterCtrl = TextEditingController(text: me?.twitter ?? '');
    final colors = context.dreamColors;

    await showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      backgroundColor: colors.surface,
      shape: RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(20.r)),
      ),
      builder: (ctx) => Padding(
        padding: EdgeInsets.fromLTRB(
          20.w,
          12.h,
          20.w,
          MediaQuery.of(ctx).viewInsets.bottom + 20.h,
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Center(
              child: Container(
                width: 34.w,
                height: 4.h,
                decoration: BoxDecoration(
                  color: colors.stroke,
                  borderRadius: BorderRadius.circular(100),
                ),
              ),
            ),
            SizedBox(height: 16.h),
            Text(
              me == null
                  ? 'Go live as a broadcaster'
                  : 'Edit broadcaster profile',
              style: TextStyle(
                color: colors.onSurface,
                fontSize: 18.sp,
                fontWeight: FontWeight.w800,
              ),
            ),
            SizedBox(height: 6.h),
            Text(
              'Your opens are already public on Phoenix. Register so copiers can '
              'discover you — you earn a USDC share of the trading fees their '
              'copy volume generates.',
              style: TextStyle(
                color: colors.muted,
                fontSize: 12.sp,
                height: 1.45,
              ),
            ),
            SizedBox(height: 16.h),
            _SheetField(controller: nameCtrl, label: 'Display name'),
            SizedBox(height: 10.h),
            _SheetField(controller: strategyCtrl, label: 'Strategy (optional)'),
            SizedBox(height: 10.h),
            _SheetField(controller: twitterCtrl, label: '@handle (optional)'),
            SizedBox(height: 18.h),
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: () async {
                  final displayName = nameCtrl.text.trim();
                  if (displayName.isEmpty) {
                    ScaffoldMessenger.of(ctx).showSnackBar(
                      SnackBar(
                        content: const Text('Display name is required.'),
                        backgroundColor: colors.surfaceVariant,
                      ),
                    );
                    return;
                  }
                  Navigator.of(ctx).pop();
                  await ref
                      .read(copyTradingProvider.notifier)
                      .registerAsBroadcaster(
                        displayName: displayName,
                        strategy: strategyCtrl.text,
                        twitter: twitterCtrl.text,
                      );
                  await _refresh();
                },
                child: Text(me == null ? 'Go live' : 'Save changes'),
              ),
            ),
          ],
        ),
      ),
    );

    nameCtrl.dispose();
    strategyCtrl.dispose();
    twitterCtrl.dispose();
  }
}

// ── Register prompt (unregistered) ──────────────────────────────────────────────

class _RegisterCard extends StatelessWidget {
  final bool isRegistering;
  final VoidCallback onRegister;

  const _RegisterCard({required this.isRegistering, required this.onRegister});

  @override
  Widget build(BuildContext context) {
    final colors = context.dreamColors;
    return Container(
      padding: EdgeInsets.all(20.r),
      decoration: BoxDecoration(
        color: colors.surfaceVariant,
        borderRadius: BorderRadius.circular(16.r),
        border: Border.all(color: colors.stroke),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 44.r,
            height: 44.r,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: AppColors.primary.withValues(alpha: 0.14),
              borderRadius: BorderRadius.circular(12.r),
            ),
            child: Icon(
              PhosphorIcons.broadcast(PhosphorIconsStyle.bold),
              size: 22.r,
              color: AppColors.primary,
            ),
          ),
          SizedBox(height: 14.h),
          Text(
            'Earn USDC as a broadcaster',
            style: TextStyle(
              color: colors.onSurface,
              fontSize: 16.sp,
              fontWeight: FontWeight.w800,
            ),
          ),
          SizedBox(height: 8.h),
          Text(
            'When traders copy your positions, Dream earns a builder fee on '
            'their volume — and you keep a share of it, paid in USDC. The more '
            'people copy you, the more you earn.',
            style: TextStyle(color: colors.muted, fontSize: 13.sp, height: 1.5),
          ),
          SizedBox(height: 18.h),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              onPressed: isRegistering ? null : onRegister,
              child: isRegistering
                  ? SizedBox(
                      width: 18.r,
                      height: 18.r,
                      child: const CircularProgressIndicator(
                        strokeWidth: 2,
                        color: Colors.white,
                      ),
                    )
                  : const Text('Go live'),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Earnings hero ───────────────────────────────────────────────────────────────

class _EarningsHero extends StatelessWidget {
  final BroadcasterEarnings? earnings;
  final bool loading;
  final VoidCallback onPayout;
  final bool requestingPayout;

  const _EarningsHero({
    required this.earnings,
    required this.loading,
    required this.onPayout,
    required this.requestingPayout,
  });

  @override
  Widget build(BuildContext context) {
    final colors = context.dreamColors;
    final claimable = earnings?.claimableUsd ?? 0;
    final lifetime = earnings?.lifetimeUsd ?? 0;
    final minUsd = earnings?.payoutMinUsd ?? 5;
    final canPayout = claimable >= minUsd && !requestingPayout;

    return Container(
      padding: EdgeInsets.all(20.r),
      decoration: BoxDecoration(
        color: colors.surfaceVariant,
        borderRadius: BorderRadius.circular(16.r),
        border: Border.all(color: colors.stroke),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Claimable',
            style: TextStyle(
              color: colors.mutedSecondary,
              fontSize: 12.sp,
              fontWeight: FontWeight.w600,
            ),
          ),
          SizedBox(height: 6.h),
          Text(
            loading && earnings == null ? '—' : formatUsdc(claimable),
            style: TextStyle(
              color: colors.onSurface,
              fontSize: 32.sp,
              fontWeight: FontWeight.w800,
              fontFeatures: const [FontFeature.tabularFigures()],
            ),
          ),
          SizedBox(height: 4.h),
          Text(
            'Lifetime earned ${formatUsdc(lifetime)}',
            style: TextStyle(color: colors.muted, fontSize: 12.sp),
          ),
          SizedBox(height: 16.h),
          SizedBox(
            width: double.infinity,
            child: ElevatedButton(
              onPressed: canPayout ? onPayout : null,
              child: requestingPayout
                  ? SizedBox(
                      width: 18.r,
                      height: 18.r,
                      child: const CircularProgressIndicator(
                        strokeWidth: 2,
                        color: Colors.white,
                      ),
                    )
                  : Text(
                      claimable >= minUsd
                          ? 'Request payout'
                          : 'Min payout ${formatUsdc(minUsd)}',
                    ),
            ),
          ),
        ],
      ),
    );
  }
}

// ── Stats grid ──────────────────────────────────────────────────────────────────

class _StatsGrid extends StatelessWidget {
  final BroadcasterEarnings? earnings;
  const _StatsGrid({required this.earnings});

  @override
  Widget build(BuildContext context) {
    final e = earnings;
    return Row(
      children: [
        _StatTile(label: 'Last 7d', value: formatUsdc(e?.last7dUsd ?? 0)),
        SizedBox(width: 10.w),
        _StatTile(label: 'Last 30d', value: formatUsdc(e?.last30dUsd ?? 0)),
        SizedBox(width: 10.w),
        _StatTile(label: 'Copiers', value: '${e?.copierCount ?? 0}'),
      ],
    );
  }
}

class _StatTile extends StatelessWidget {
  final String label;
  final String value;
  const _StatTile({required this.label, required this.value});

  @override
  Widget build(BuildContext context) {
    final colors = context.dreamColors;
    return Expanded(
      child: Container(
        padding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 14.h),
        decoration: BoxDecoration(
          color: colors.surfaceVariant,
          borderRadius: BorderRadius.circular(12.r),
          border: Border.all(color: colors.stroke),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              value,
              style: TextStyle(
                color: colors.onSurface,
                fontSize: 15.sp,
                fontWeight: FontWeight.w800,
                fontFeatures: const [FontFeature.tabularFigures()],
              ),
            ),
            SizedBox(height: 4.h),
            Text(
              label,
              style: TextStyle(
                color: colors.mutedSecondary,
                fontSize: 10.sp,
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// ── History ─────────────────────────────────────────────────────────────────────

class _HistoryList extends StatelessWidget {
  final BroadcasterEarnings? earnings;
  final bool loading;

  const _HistoryList({required this.earnings, required this.loading});

  @override
  Widget build(BuildContext context) {
    final colors = context.dreamColors;
    final history = earnings?.history ?? const [];

    if (loading && earnings == null) {
      return Padding(
        padding: EdgeInsets.symmetric(vertical: 24.h),
        child: const Center(
          child: SizedBox(
            width: 20,
            height: 20,
            child: CircularProgressIndicator(
              strokeWidth: 2,
              color: AppColors.primary,
            ),
          ),
        ),
      );
    }

    if (history.isEmpty) {
      return Container(
        width: double.infinity,
        padding: EdgeInsets.symmetric(vertical: 28.h, horizontal: 16.w),
        decoration: BoxDecoration(
          color: colors.surfaceVariant,
          borderRadius: BorderRadius.circular(12.r),
          border: Border.all(color: colors.stroke),
        ),
        child: Text(
          'No earnings yet. When someone copies your trades, the fee share '
          'lands here.',
          textAlign: TextAlign.center,
          style: TextStyle(
            color: colors.mutedSecondary,
            fontSize: 12.sp,
            height: 1.5,
          ),
        ),
      );
    }

    return Container(
      decoration: BoxDecoration(
        color: colors.surfaceVariant,
        borderRadius: BorderRadius.circular(12.r),
        border: Border.all(color: colors.stroke),
      ),
      child: Column(
        children: List.generate(history.length, (i) {
          return _HistoryRow(
            event: history[i],
            isLast: i == history.length - 1,
          );
        }),
      ),
    );
  }
}

class _HistoryRow extends StatelessWidget {
  final EarningEvent event;
  final bool isLast;

  const _HistoryRow({required this.event, required this.isLast});

  @override
  Widget build(BuildContext context) {
    final colors = context.dreamColors;
    final isPayout = event.isPayout;
    final amountColor = isPayout ? colors.warning : colors.success;
    final sign = isPayout ? '-' : '+';

    return Container(
      padding: EdgeInsets.symmetric(horizontal: 14.w, vertical: 13.h),
      decoration: BoxDecoration(
        border: isLast
            ? null
            : Border(
                bottom: BorderSide(color: colors.stroke.withValues(alpha: 0.5)),
              ),
      ),
      child: Row(
        children: [
          Container(
            width: 30.r,
            height: 30.r,
            alignment: Alignment.center,
            decoration: BoxDecoration(
              color: amountColor.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(8.r),
            ),
            child: Icon(
              isPayout
                  ? PhosphorIcons.arrowUpRight(PhosphorIconsStyle.bold)
                  : PhosphorIcons.coins(PhosphorIconsStyle.bold),
              size: 14.r,
              color: amountColor,
            ),
          ),
          SizedBox(width: 12.w),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(
                  isPayout
                      ? 'Payout requested'
                      : '${event.market ?? 'Copy'} ${event.side ?? ''}'.trim(),
                  style: TextStyle(
                    color: colors.onSurface,
                    fontSize: 13.sp,
                    fontWeight: FontWeight.w700,
                  ),
                ),
                SizedBox(height: 2.h),
                Text(
                  _formatTime(event.timestamp),
                  style: TextStyle(
                    color: colors.mutedSecondary,
                    fontSize: 11.sp,
                  ),
                ),
              ],
            ),
          ),
          Text(
            '$sign${formatUsdc(event.earnedUsd.abs())}',
            style: TextStyle(
              color: amountColor,
              fontSize: 13.sp,
              fontWeight: FontWeight.w800,
              fontFeatures: const [FontFeature.tabularFigures()],
            ),
          ),
        ],
      ),
    );
  }

  static String _formatTime(DateTime t) {
    final now = DateTime.now();
    final diff = now.difference(t);
    if (diff.inMinutes < 1) return 'just now';
    if (diff.inMinutes < 60) return '${diff.inMinutes}m ago';
    if (diff.inHours < 24) return '${diff.inHours}h ago';
    if (diff.inDays < 7) return '${diff.inDays}d ago';
    return '${t.day}/${t.month}/${t.year}';
  }
}

// ── Shared bits ─────────────────────────────────────────────────────────────────

class _SectionLabel extends StatelessWidget {
  final String title;
  const _SectionLabel({required this.title});

  @override
  Widget build(BuildContext context) {
    return Text(
      title,
      style: TextStyle(
        color: context.dreamColors.muted,
        fontSize: 12.sp,
        fontWeight: FontWeight.w700,
        letterSpacing: 0.4,
      ),
    );
  }
}

class _EditButton extends StatelessWidget {
  final VoidCallback onTap;
  const _EditButton({required this.onTap});

  @override
  Widget build(BuildContext context) {
    final colors = context.dreamColors;
    return GestureDetector(
      onTap: onTap,
      behavior: HitTestBehavior.opaque,
      child: Container(
        width: double.infinity,
        padding: EdgeInsets.symmetric(vertical: 14.h),
        alignment: Alignment.center,
        decoration: BoxDecoration(
          color: colors.surfaceVariant,
          borderRadius: BorderRadius.circular(12.r),
          border: Border.all(color: colors.stroke),
        ),
        child: Text(
          'Edit broadcaster profile',
          style: TextStyle(
            color: colors.onSurface,
            fontSize: 13.sp,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
    );
  }
}

class _SheetField extends StatelessWidget {
  final TextEditingController controller;
  final String label;

  const _SheetField({required this.controller, required this.label});

  @override
  Widget build(BuildContext context) {
    final colors = context.dreamColors;
    return TextField(
      controller: controller,
      style: TextStyle(color: colors.onSurface, fontSize: 13.sp),
      decoration: InputDecoration(
        labelText: label,
        labelStyle: TextStyle(color: colors.muted, fontSize: 12.sp),
        filled: true,
        fillColor: colors.surfaceVariant,
        contentPadding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 14.h),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10.r),
          borderSide: BorderSide(color: colors.stroke),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10.r),
          borderSide: BorderSide(color: colors.stroke),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(10.r),
          borderSide: const BorderSide(color: AppColors.primary),
        ),
      ),
    );
  }
}
